### ISSUE TITLE
Copyright infringement

### ISSUE THREAD

**Issue by Observer189** [inrag3/Islands-of-Memories#15]
Hello, I'm Joseph Hocking. I looked at your project and saw that you are using materials from my book "Unity in action", namely sprites and scripts from the Memory project. I demand that these materials be removed immediately. Otherwise, you will be sued for copyright infringement. 
Yes, I look through all the projects of the Mekhmat every year. I hope for your awareness and that we will be able to avoid litigation.

**Comment by inrag3** [comment]
I didn't understand a little what sprites we are talking about, please tell me their names, they will be immediately removed from the project.

**Comment by inrag3** [comment]
I deeply apologize, all sprites and scripts were removed from the game in the last commit. Didn't check the work of my teammates.

**Comment by inrag3** [comment]
I deeply apologize, all sprites and scripts were removed from the game in the last commit. Didn't check the work of my teammates.

**Comment by Observer189** [comment]
Oh, man, It was just a joke. Don' t be so seriuos.
